### PR TITLE
modify how serialize forest accesses trees

### PR DESCRIPTION
**Pull request by crflynn**
In attempting to build wheels, linux runners manifest the following error:

https://github.com/crflynn/skgrf-wheels/pull/1/checks?check_run_id=2318777493

```
skgrf/ensemble/grf.cpp: In function ‘PyObject* __pyx_f_5skgrf_8ensemble_3grf_serialize_forest(grf::Forest*)’:
skgrf/ensemble/grf.cpp:9392:109: error: call of overloaded ‘move(__gnu_cxx::__alloc_traits<std::allocator<std::unique_ptr<grf::Tree> > >::value_type&)’ is ambiguous
     __pyx_v_tree = cython_std::move<std::unique_ptr<grf::Tree>  &>((__pyx_v_forest->get_trees_()[__pyx_v_t]));
```

This removes the `move` but it is then a bit challenging to otherwise simplify this code. Hopefully this eliminates the compilation errors.

### CODE REVIEW

**Comment by erikcs** [comment]
Hi @crflynn, you can probably drop the serialization step for your python bindings all-together if you want, the only reason it's done in the R package is for R's native `save` to work.

An alternative where the wrapper just holds a pointer to the forest is here:https://github.com/grf-labs/grf/pull/598, assume you can do something similar in Cython, unless you want to implement pickle support you don't have to serialize.

**Comment by erikcs** [comment]
You might also want to increase the default number of trees in causal forest, 100 will typically not give great kernel weights. If you are using 100 as the default because of sklearn, I can imagine it's that low because of speed (which isn't much of an issue since grf is faster)

**Comment by crflynn** [comment]
Will address that as well. Feel free to open issues on anything else you notice and I'll do my best to address them.

**Comment by erikcs** [comment]
Also feel free to @ me if you have any questions.

**Pull request merged**
